### ISSUE TITLE
Drivable Segmentation Model inference stuck

### ISSUE THREAD

**Issue by danielzhangau** [SysCV/bdd100k-models#6]
When I am running `Deeplabv3+` model by using:
`python ./test.py configs/drivable/deeplabv3plus_r50-d8_512x1024_40k_drivable_bdd100k.py --format-only --format-dir output`
It just stuck in around 1490 step
![image](https://user-images.githubusercontent.com/41173132/143347422-a471bb73-5ba2-4acf-9d4f-54546c6ebe12.png)
I have tried several different configs, they all have the same issue.

**Comment by thomasehuang** [comment]
Can you provide your exact environment details so I can try to reproduce the issue?

**Comment by danielzhangau** [comment]
Hi, here below is my all packages installed under the environment: 
```
Package           Version
----------------- ---------
addict            2.4.0
certifi           2021.10.8
cycler            0.11.0
fonttools         4.28.2
kiwisolver        1.3.2
matplotlib        3.5.0
mkl-fft           1.3.1
mkl-random        1.2.2
mkl-service       2.4.0
mmcv-full         1.3.18
mmsegmentation    0.19.0
numpy             1.21.2
olefile           0.46
opencv-python     4.5.4.60
packaging         21.3
Pillow            8.4.0
pip               21.3.1
prettytable       2.4.0
pyparsing         3.0.6
python-dateutil   2.8.2
PyYAML            6.0
setuptools        58.0.4
setuptools-scm    6.3.2
six               1.16.0
tomli             1.2.2
torch             1.10.0
torchaudio        0.10.0
torchvision       0.11.1
typing-extensions 3.10.0.2
wcwidth           0.2.5
wheel             0.37.0
yapf              0.31.0
```

**Comment by danielzhangau** [comment]
It has the issue when I run this line (this is an example)
`python test.py configs/drivable/deeplabv3_r50-d8_512x1024_40k_drivable_bdd100k.py --format-only --format-dir output`

**Comment by thomasehuang** [comment]
Hmm, this could either be due to memory issues or the version of `mmsegmentation` or `mmcv`. Maybe first monitor the memory usage and see if that's causing problems, since `mmsegmentation`'s inference uses quite a bit. For the packages, for reference I am using `mmsegmentation==0.17.0` and `mmcv-full==1.3.9`. I can run some tests later to see which versions potentially break the code, but maybe if the memory isn't an issue you can try downgrading the packages and seeing if it works?
